Minor: Remove the warning when an event apart from To-Device is received
matrix-org/waterfall pull request #60
Opened 2022-12-05 19:22 UTC by daniel-abramov

Not sure what type of events we receive, but every time I start a server, I get like 30 warnings. I.e. it seems like we always receive some non-to-device messages when we start an SFU.

@SimonBrandner do you by chance know what this stuff is and if we need it at all?

I would recommend removing this warning since it spams too many messages when it happens.

2022-12-05 20:36 UTC, SimonBrandner requested changes
Let's figure out what these are before we remove the warning: https://github.com/matrix-org/waterfall/issues/61

2022-12-06 08:33 UTC, SimonBrandner commented on pkg/signaling/client.go
>  		// We only care about to-device events.
```suggestion
		// We only care about to-device events but also receive m.presence and
		// m.push_rules events; we can simply ignore those.
```

2022-12-06 08:34 UTC, SimonBrandner requested changes
LGTM after the added comment

2022-12-06 10:58 UTC, daniel-abramov commented
> Let's figure out what these are before we remove the warning: #61

You seem to have figured it out already, right? :)

OT: Btw, the presence events don't seem to be used by Element Web and Element Desktop, right?

2022-12-06 10:59 UTC, daniel-abramov commented
> LGTM after the added comment

Done!

2022-12-06 11:08 UTC, SimonBrandner approved these changes

2022-12-06 11:10 UTC, merged